INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (101, 'Материнская карта', '1', 5);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (102, 'Звуковая карта', null, 3);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (104, 'Процессор', '1', 6);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (519, 'Зарядное устройство', null, 50);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (620, 'Микрофон', '1', 40);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (621, 'Ручка', null, 50);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (110, 'Монитор', null, 5);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (211, 'Наушники', null, 12);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (312, 'Клавиатура', '1', 5);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (213, 'Флеш-карта', '1', 100);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (214, 'Мышка', '1', 50);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (315, 'Конденсатор', null, 100);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (105, 'Подсветка корпуса', null, 3);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (103, 'Корпус', null, 15);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (117, 'Память', '1', 2);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (108, 'SSD диска', null, 10);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (109, 'Видеокарта', null, 4);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (316, 'Паяльник', null, 2);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (317, 'Коврик для мышки', '1', 50);
INSERT INTO test.part (id, namePart, isBuild, quantity) VALUES (418, 'Пленка для монитора', '1', 20);
